version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      # Log in to ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 575108947704.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      # Build the Docker image
      - docker build -t swat_app .
      - docker tag swat_app:latest 575108947704.dkr.ecr.ap-south-1.amazonaws.com/swat_app:latest
  post_build:
    commands:
      # Push the Docker image to ECR
      - docker push 575108947704.dkr.ecr.ap-south-1.amazonaws.com/swat_app:latest
